name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - name: Run danger-action
        uses: ./
        with:
          gemfile: test/Gemfile
          dangerfile: test/Dangerfile
